name: OpenAI Text to SQL Intelligent Conversion
description: |
  Leverage OpenAI for intelligent conversion of Text to SQL based on context from database table schemas.

author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-09-11"

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: 0_session-install-deps/install_dependencies.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 8
  
  - type: start_application
    name: CML OpenAI Text to SQL
    subdomain: cmlllm
    script: 1_app/llm_rag_app.py
    short_summary: Start CML OpenAI Text to SQL application
    long_summary: Because this AMP leverages OpenAI, you do not need GPUs to run it; however, there are minimum resource constraints which must be met for CPU and Memory availability.
    cpu: 2
    memory: 16
    environment_variables:
      TASK_TYPE: START_APPLICATION
